/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/EditableTextInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/EditingToggle`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExchangeRates`; params?: Router.UnknownInputParams; } | { pathname: `/context/ExchangeRates/ExchangeRatesProvider`; params?: Router.UnknownInputParams; } | { pathname: `/context/ExchangeRates/context`; params?: Router.UnknownInputParams; } | { pathname: `/utils/consts`; params?: Router.UnknownInputParams; } | { pathname: `/views/ExchangeRates`; params?: Router.UnknownInputParams; } | { pathname: `/views/ExchangeRates/types`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/app`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EditableTextInput`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EditingToggle`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ExchangeRates`; params?: Router.UnknownOutputParams; } | { pathname: `/context/ExchangeRates/ExchangeRatesProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/context/ExchangeRates/context`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/consts`; params?: Router.UnknownOutputParams; } | { pathname: `/views/ExchangeRates`; params?: Router.UnknownOutputParams; } | { pathname: `/views/ExchangeRates/types`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/app${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/EditableTextInput${`?${string}` | `#${string}` | ''}` | `/components/EditingToggle${`?${string}` | `#${string}` | ''}` | `/components/ExchangeRates${`?${string}` | `#${string}` | ''}` | `/context/ExchangeRates/ExchangeRatesProvider${`?${string}` | `#${string}` | ''}` | `/context/ExchangeRates/context${`?${string}` | `#${string}` | ''}` | `/utils/consts${`?${string}` | `#${string}` | ''}` | `/views/ExchangeRates${`?${string}` | `#${string}` | ''}` | `/views/ExchangeRates/types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/EditableTextInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/EditingToggle`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExchangeRates`; params?: Router.UnknownInputParams; } | { pathname: `/context/ExchangeRates/ExchangeRatesProvider`; params?: Router.UnknownInputParams; } | { pathname: `/context/ExchangeRates/context`; params?: Router.UnknownInputParams; } | { pathname: `/utils/consts`; params?: Router.UnknownInputParams; } | { pathname: `/views/ExchangeRates`; params?: Router.UnknownInputParams; } | { pathname: `/views/ExchangeRates/types`; params?: Router.UnknownInputParams; };
    }
  }
}
